"""
survpfn.dataloaders.data_utils.eicu_survival
--------------------------------------------
Loader for the eICU-CRD in-ICU survival dataset.

Generated by:
  ehrmeds/static/survival/eicu/run_survival_eicu.sh

Expected file layout:
  data/eicu_survival.csv
    Columns: patientunitstayid, ..., survival_hours (T), mortality (E), features...

Set EICU_SURV_PATH env var to override the default path.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

from survpfn.dataloaders.data_utils.utils import (
    _drop_low_prevalence_binary,
    _drop_duplicate_columns,
)

_DEFAULT_PATH = Path(os.environ.get(
    "EICU_SURV_PATH",
    Path(__file__).resolve().parents[3] / "data" / "eicu_survival.csv",
))

# Columns that are identifiers, not features
_ID_COLS = {"patientunitstayid", "patienthealthsystemstayid", "uniquepid", "hospitalid"}

_DURATION_COL = "survival_hours"
_EVENT_COL    = "mortality"


def load_eicu_survival(path: Path = _DEFAULT_PATH) -> tuple[pd.DataFrame, str, str]:
    """
    Load eICU-CRD in-ICU all-cause mortality survival dataset.

    Post-load cleaning applied automatically:
    - Sparse binary features (ICD10 chapters, TREAT_* flags) with fewer than
      5 observations in either class are dropped to prevent CoxPH complete-
      separation warnings (lifelines ConvergenceWarning).
    - Byte-identical columns are deduplicated (handles single-measurement
      lab aggregates where min=max=mean).

    Returns
    -------
    (df, duration_col, event_col)
        df            : pd.DataFrame with one row per first ICU stay
        duration_col  : "survival_hours"  (float, hours from ICU admission)
        event_col     : "mortality"       (int, 1 = in-ICU death)
    """
    df = pd.read_csv(path, low_memory=False)

    # Drop identifier columns — keep only modelling columns
    drop_cols = [c for c in _ID_COLS if c in df.columns]
    df = df.drop(columns=drop_cols)

    _exclude = [_DURATION_COL, _EVENT_COL]

    # Drop sparse binary features (prevents CoxPH complete-separation warnings)
    # event_col enables stratum-aware check: drops ICD10 chapters that appear
    # in <5 event=1 patients even if overall count is ≥5
    df = _drop_low_prevalence_binary(df, exclude_cols=_exclude, min_count=5,
                                     event_col=_EVENT_COL)

    # Drop byte-identical duplicate columns
    df = _drop_duplicate_columns(df, exclude_cols=_exclude)

    return df, _DURATION_COL, _EVENT_COL
