"""
survpfn.dataloaders.data_utils.eicu_survival
--------------------------------------------
Loader for the eICU-CRD in-ICU survival dataset.

Generated by:
  ehrmeds/static/survival/eicu/run_survival_eicu.sh

Expected file layout:
  data/eicu_survival.csv
    Columns: patientunitstayid, ..., survival_hours (T), mortality (E), features...

Set EICU_SURV_PATH env var to override the default path.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

_DEFAULT_PATH = Path(os.environ.get(
    "EICU_SURV_PATH",
    Path(__file__).resolve().parents[3] / "data" / "eicu_survival.csv",
))

# Columns that are identifiers, not features
_ID_COLS = {"patientunitstayid", "patienthealthsystemstayid", "uniquepid", "hospitalid"}


def load_eicu_survival(path: Path = _DEFAULT_PATH) -> tuple[pd.DataFrame, str, str]:
    """
    Load eICU-CRD in-ICU all-cause mortality survival dataset.

    Returns
    -------
    (df, duration_col, event_col)
        df            : pd.DataFrame with one row per first ICU stay
        duration_col  : "survival_hours"  (float, hours from ICU admission)
        event_col     : "mortality"       (int, 1 = in-ICU death)
    """
    df = pd.read_csv(path, low_memory=False)

    # Drop identifier columns — keep only modelling columns
    drop_cols = [c for c in _ID_COLS if c in df.columns]
    df = df.drop(columns=drop_cols)

    return df, "survival_hours", "mortality"
