"""
survpfn.dataloaders.data_utils.mimic_survival
---------------------------------------------
Loader for the MIMIC-IV in-hospital survival dataset (Task B).

Generated by:
  ehrmeds/static/survival/mimiciv/run_survival_mimiciv.sh

Expected file layout:
  data/mimiciv_survival_B.csv
    Columns: subject_id, hadm_id, stay_id, survival_hours (T), mortality (E), features...

Set MIMIC_SURV_B_PATH env var to override the default path.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

_DEFAULT_PATH_B = Path(os.environ.get(
    "MIMIC_SURV_B_PATH",
    Path(__file__).resolve().parents[3] / "data" / "mimiciv_survival_B.csv",
))

_ID_COLS = {"subject_id", "hadm_id", "stay_id"}


def load_mimiciv_survival_B(path: Path = _DEFAULT_PATH_B) -> tuple[pd.DataFrame, str, str]:
    """
    Load MIMIC-IV in-hospital all-cause mortality survival dataset (Task B).

    Returns
    -------
    (df, duration_col, event_col)
        df            : pd.DataFrame with one row per first ICU stay
        duration_col  : "survival_hours"  (float, hours from ICU admission to discharge/death)
        event_col     : "mortality"       (int, 1 = in-hospital death)
    """
    df = pd.read_csv(path, low_memory=False)
    drop_cols = [c for c in _ID_COLS if c in df.columns]
    df = df.drop(columns=drop_cols)
    return df, "survival_hours", "mortality"
